/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "sprintf.check" instead.
 */

#include <check.h>

#line 1 "sprintf.check"
#include "struct.h"

START_TEST(normal_test)
{
#line 4
    char bufferTrue[100];
    char bufferTest[100];
    int age = 25;
    float height = 1.75;
    sprintf(bufferTrue, "Age: %d, Height: %.2f meters", age, height);
    s21_sprintf(bufferTest, "Age: %d, Height: %.2f meters", age, height);
    printf("%zu\n%zu", strlen(bufferTest), strlen(bufferTrue));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, normal_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
